downloader:
  output_path: "/output/"
  max_duration_in_seconds: 660
scraper:
  twitch_tracker:
    url: "https://twitchtracker.com/games"
    game_id: "538054672"
    time_start: "20240513"
    time_end: "20240515"
setup:
  db_url: "mongodb://localhost:27017"
