downloader:
  output_path: "/output/"
  max_duration_in_seconds: 660
scraper:
  twitch_tracker:
    url: "https://twitchtracker.com/games"
    game_id: "516575"
    time_start: "20240608"
    time_end: "20240610"
setup:
  db_url: "mongodb://localhost:27017"
